"""results/bench/*.json + results/verify/*.json -> results/charts/*.png and results/bench/summary.md

    uv run python bench/plot.py

Colors: fixed categorical order (validated with the dataviz palette checker):
tinyserve = blue, vLLM = orange, HF reference = aqua, paper = yellow. Aqua and
yellow are below 3:1 contrast on white, so every bar carries a visible value
label and every chart has a table in summary.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BENCH, VERIFY, CHARTS = ROOT / "results" / "bench", ROOT / "results" / "verify", ROOT / "results" / "charts"
COLORS = {"tinyserve": "#2a78d6", "vllm": "#eb6834", "reference": "#1baf7a", "paper": "#eda100"}
INK, INK2, GRID, SURFACE = "#0b0b0b", "#52514e", "#e4e3df", "#fcfcfb"
LABEL = {"tinyserve": "tinyserve", "vllm": "vLLM", "reference": "z-lab reference (HF)", "paper": "DFlash paper"}

plt.rcParams.update({
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE, "axes.edgecolor": GRID, "axes.labelcolor": INK2,
    "xtick.color": INK2, "ytick.color": INK2, "text.color": INK, "axes.grid": True, "grid.color": GRID,
    "grid.linewidth": 0.8, "axes.spines.top": False, "axes.spines.right": False, "font.size": 10,
    "legend.frameon": False, "axes.titlesize": 12, "axes.titleweight": "bold", "axes.titlelocation": "left",
})


def load_bench() -> dict:
    """key 'engine/key' -> result (latest file wins)."""
    out = {}
    for f in sorted(BENCH.glob("*.json")):
        r = json.loads(f.read_text(encoding="utf-8"))
        if "points" in r:
            out[f"{r['engine']}/{r.get('key', r['workload'])}"] = r
    return out


def pts(r, repeat=False):
    return sorted((p for p in r["points"] if p.get("repeat", False) == repeat), key=lambda p: p["concurrency"])


def subtitle(ax, text):
    ax.text(0, 1.02, text, transform=ax.transAxes, color=INK2, fontsize=9, va="bottom")


def line_chart(bench, key, metric, ylabel, title, fname, log_y=False, sub=""):
    fig, ax = plt.subplots(figsize=(7, 4.2))
    drawn = False
    for eng in ("tinyserve", "vllm"):
        r = bench.get(f"{eng}/{key}")
        if not r:
            continue
        p = pts(r)
        xs = [q["concurrency"] for q in p]
        ys = [metric(q) for q in p]
        ax.plot(xs, ys, color=COLORS[eng], lw=2, marker="o", ms=8, mec=SURFACE, mew=2, label=LABEL[eng])
        ax.annotate(f"{ys[-1]:,.0f}", (xs[-1], ys[-1]), xytext=(6, 0), textcoords="offset points", color=INK2, va="center", fontsize=9)
        drawn = True
    if not drawn:
        plt.close(fig)
        return False
    ax.set_xscale("log", base=2)
    if log_y:
        ax.set_yscale("log")
    ax.set_xticks(W1 := [1, 4, 16, 64, 128], [str(x) for x in W1])
    ax.set_xlabel("concurrent requests (closed loop)")
    ax.set_ylabel(ylabel)
    ax.set_title(title, pad=22)
    subtitle(ax, sub)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(CHARTS / fname, dpi=150)
    plt.close(fig)
    return True


def bar_chart(groups: list[tuple[str, float, str]], ylabel, title, fname, sub="", fmt="{:.0f}"):
    fig, ax = plt.subplots(figsize=(7, 4.2))
    xs = range(len(groups))
    bars = ax.bar(xs, [g[1] for g in groups], color=[COLORS[g[2]] for g in groups], width=0.6, edgecolor=SURFACE, linewidth=2)
    for b, g in zip(bars, groups):
        ax.annotate(fmt.format(g[1]), (b.get_x() + b.get_width() / 2, b.get_height()), xytext=(0, 3),
                    textcoords="offset points", ha="center", color=INK, fontsize=9)
    ax.set_xticks(list(xs), [g[0] for g in groups])
    ax.set_ylabel(ylabel)
    ax.set_title(title, pad=22)
    subtitle(ax, sub)
    ax.grid(axis="x", visible=False)
    fig.tight_layout()
    fig.savefig(CHARTS / fname, dpi=150)
    plt.close(fig)


def main() -> None:
    CHARTS.mkdir(parents=True, exist_ok=True)
    bench = load_bench()
    lines = ["# Benchmark summary (auto-generated by `bench/plot.py`)", ""]
    gpu = next((r["gpu"] for r in bench.values()), "NVIDIA L4")
    vver = next((r["engine_version"] for k, r in bench.items() if k.startswith("vllm/")), "n/a")
    tver = next((r["engine_version"] for k, r in bench.items() if k.startswith("tinyserve/")), "n/a")
    lines += [f"GPU: {gpu}. tinyserve git `{tver}`, vLLM `{vver}`. Raw data: `results/bench/*.json`.", ""]

    # 1-2: W1
    sub = "W1: Qwen3-0.6B bf16, 256 requests, input U[256,768], output 256"
    line_chart(bench, "W1", lambda p: p["output_tok_s"], "output tokens / s", "Throughput vs concurrency", "throughput_vs_concurrency.png", sub=sub)
    line_chart(bench, "W1", lambda p: p["ttft_ms"]["p50"], "TTFT p50 (ms, log)", "Time to first token", "ttft_p50_vs_concurrency.png", log_y=True, sub=sub)
    line_chart(bench, "W1", lambda p: p["tpot_ms"]["p50"], "TPOT p50 (ms / token)", "Time per output token", "tpot_p50_vs_concurrency.png", sub=sub)
    if "tinyserve/W1" in bench or "vllm/W1" in bench:
        lines += ["## W1 (random lengths, Qwen3-0.6B)", "", "| c | engine | out tok/s | TTFT p50 ms | TTFT p99 ms | TPOT p50 ms | ITL p50 ms | errors |", "|---|---|---|---|---|---|---|---|"]
        for eng in ("tinyserve", "vllm"):
            r = bench.get(f"{eng}/W1")
            if r:
                for p in pts(r) + pts(r, True):
                    lines.append(f"| {p['concurrency']}{' (repeat)' if p.get('repeat') else ''} | {eng} | {p['output_tok_s']:,.0f} | {p['ttft_ms']['p50']:.1f} | "
                                 f"{p['ttft_ms']['p99']:.1f} | {p['tpot_ms']['p50']:.2f} | {p['itl_ms']['p50']:.2f} | {p['errors']} |")
        t, v = bench.get("tinyserve/W1"), bench.get("vllm/W1")
        if t and v:
            lines += ["", "| c | tinyserve / vLLM throughput |", "|---|---|"]
            for a, b in zip(pts(t), pts(v)):
                lines.append(f"| {a['concurrency']} | {a['output_tok_s'] / b['output_tok_s']:.1%} |")
        lines.append("")

    # 3: W2 prefix cache
    g = []
    for label, key, eng in (("tinyserve\ncache off", "W2_cacheoff", "tinyserve"), ("tinyserve\ncache on", "W2_cacheon", "tinyserve"), ("vLLM\ncache on", "W2_cacheon", "vllm")):
        r = bench.get(f"{eng}/{key}")
        if r:
            g.append((label, pts(r)[0]["ttft_ms"]["p50"], eng))
    if g:
        bar_chart(g, "TTFT p50 (ms)", "Prefix caching: time to first token", "prefix_cache_ttft.png",
                  sub="W2: 8 groups x 16 requests, 2048-token shared prefix + 64-128 unique, c=16")
        lines += ["## W2 (shared prefix, c=16)", "", "| config | TTFT p50 ms | TTFT p99 ms | out tok/s |", "|---|---|---|---|"]
        for label, key, eng in (("tinyserve cache off", "W2_cacheoff", "tinyserve"), ("tinyserve cache on", "W2_cacheon", "tinyserve"), ("vLLM cache on", "W2_cacheon", "vllm")):
            r = bench.get(f"{eng}/{key}")
            if r:
                p = pts(r)[0]
                lines.append(f"| {label} | {p['ttft_ms']['p50']:.1f} | {p['ttft_ms']['p99']:.1f} | {p['output_tok_s']:,.0f} |")
        lines.append("")

    # 4: spec speedup vs concurrency (gsm8k)
    fig, ax = plt.subplots(figsize=(7, 4.2))
    drawn = False
    spec_rows = []
    variants = [("tinyserve", "W3-gsm8k_dflash_graphs", "tinyserve DFlash (graph verify, M9c) ÷ tinyserve", "-", (6, -16)),
                ("tinyserve", "W3-gsm8k_dflash", "tinyserve DFlash (eager verify, M7) ÷ tinyserve", "--", (6, 6)),
                ("vllm", "W3-gsm8k_dflash", "vLLM DFlash ÷ vLLM", "-", (6, 6))]
    for eng, key, label, ls, off in variants:
        base, fl = bench.get(f"{eng}/W3-gsm8k_base"), bench.get(f"{eng}/{key}")
        if not (base and fl):
            continue
        b, f = {p["concurrency"]: p for p in pts(base)}, {p["concurrency"]: p for p in pts(fl)}
        cs = sorted(set(b) & set(f))
        sp = [f[c]["output_tok_s"] / b[c]["output_tok_s"] for c in cs]
        ax.plot(cs, sp, color=COLORS[eng], lw=2, ls=ls, marker="o", ms=8, mec=SURFACE, mew=2, label=label)
        ax.annotate(f"{sp[0]:.2f}x", (cs[0], sp[0]), xytext=off, textcoords="offset points", color=INK2, fontsize=9)
        drawn = True
        name = label.split(" ÷")[0]
        for c, x in zip(cs, sp):
            spec_rows.append(f"| {c} | {name} | {b[c]['output_tok_s']:,.1f} | {f[c]['output_tok_s']:,.1f} | {x:.2f}x | {f[c].get('tau')} |")
    if drawn:
        ax.axhline(1, color=INK2, lw=1, ls="--")
        ax.set_xscale("log", base=2)
        ax.set_xticks([1, 2, 4, 8, 16], ["1", "2", "4", "8", "16"])
        ax.set_xlabel("concurrent requests")
        ax.set_ylabel("speedup in output tokens / s (x)")
        ax.set_title("DFlash speedup vs concurrency", pad=22)
        subtitle(ax, "W3 GSM8K: Qwen3-4B bf16 + z-lab/Qwen3-4B-DFlash-b16, greedy, max 512 tokens")
        ax.set_ylim(0, 5)
        ax.legend(loc="lower right", fontsize=9)
        fig.tight_layout()
        fig.savefig(CHARTS / "spec_speedup_vs_concurrency.png", dpi=150)
        lines += ["## W3 GSM8K: DFlash speedup", "", "| c | config | base tok/s | DFlash tok/s | speedup | tau |", "|---|---|---|---|---|---|", *spec_rows, ""]
    plt.close(fig)

    # 5: tau vs paper
    from bench.workloads import PAPER_TAU_QWEN3_4B, SPEC_DATASETS

    m7 = json.loads((VERIFY / "m7.json").read_text()) if (VERIFY / "m7.json").exists() else {}
    mm = m7.get("metrics", {})
    series = {"tinyserve": mm.get("tinyserve_tau_all32_c16", {}), "reference": mm.get("ref_tau", {}),
              "vllm": {d: pts(r)[-1].get("tau") for d in SPEC_DATASETS if (r := bench.get(f"vllm/W3-{d}_dflash"))},
              "paper": PAPER_TAU_QWEN3_4B}
    series = {k: v for k, v in series.items() if v and any(x for x in v.values())}
    if series:
        fig, ax = plt.subplots(figsize=(7.5, 4.2))
        w = 0.8 / len(series)
        for i, (k, v) in enumerate(series.items()):
            xs = [j + (i - (len(series) - 1) / 2) * w for j in range(len(SPEC_DATASETS))]
            ys = [v.get(d) or 0 for d in SPEC_DATASETS]
            bars = ax.bar(xs, ys, w * 0.9, color=COLORS[k], label=LABEL[k], edgecolor=SURFACE, linewidth=2)
            for b, y in zip(bars, ys):
                if y:
                    ax.annotate(f"{y:.2f}", (b.get_x() + b.get_width() / 2, y), xytext=(0, 3), textcoords="offset points", ha="center", fontsize=8, color=INK)
        ax.set_xticks(range(len(SPEC_DATASETS)), ["GSM8K", "HumanEval", "MT-Bench"])
        ax.set_ylabel("mean acceptance length τ (tokens / step)")
        ax.set_title("DFlash acceptance length vs paper", pad=22)
        subtitle(ax, "Qwen3-4B, greedy, max 512 tokens (paper: 2048). Reference: 8 prompts, bs=1; tinyserve/vLLM: 32, c=16")
        ax.set_ylim(0, 8.6)
        ax.legend(loc="upper center", ncols=4, fontsize=9)
        ax.grid(axis="x", visible=False)
        fig.tight_layout()
        fig.savefig(CHARTS / "tau_vs_paper.png", dpi=150)
        plt.close(fig)
        lines += ["## DFlash tau per dataset", "", "| source | " + " | ".join(SPEC_DATASETS) + " |", "|---|---|---|---|"]
        for k, v in series.items():
            lines.append(f"| {LABEL[k]} | " + " | ".join(f"{v[d]:.2f}" if v.get(d) else "n/a" for d in SPEC_DATASETS) + " |")
        lines.append("")

    # 6: CUDA graph ITL (M5)
    m5 = json.loads((VERIFY / "m5.json").read_text()) if (VERIFY / "m5.json").exists() else {}
    sweep = m5.get("metrics", {}).get("itl_sweep")
    if sweep:
        bss = sorted(int(b) for b in sweep)
        fig, ax = plt.subplots(figsize=(7, 4.2))
        for k, label, color in (("eager_ms", "eager", COLORS["vllm"]), ("graph_ms", "CUDA graphs", COLORS["tinyserve"])):
            ys = [sweep[str(b)][k] for b in bss]
            ax.plot(bss, ys, color=color, lw=2, marker="o", ms=8, mec=SURFACE, mew=2, label=f"tinyserve {label}")
            ax.annotate(f"{ys[0]:.1f} ms", (bss[0], ys[0]), xytext=(6, 6), textcoords="offset points", color=INK2, fontsize=9)
        ax.set_xscale("log", base=2)
        ax.set_xticks(bss, [str(b) for b in bss])
        ax.set_ylim(bottom=0)
        ax.set_xlabel("decode batch size")
        ax.set_ylabel("inter-token latency p50 (ms)")
        ax.set_title("CUDA graphs remove CPU launch overhead", pad=22)
        subtitle(ax, "Qwen3-0.6B bf16 decode, L4 (M5 verification run)")
        ax.legend(loc="best")
        fig.tight_layout()
        fig.savefig(CHARTS / "cuda_graph_itl.png", dpi=150)
        plt.close(fig)
        lines += ["## CUDA graphs (M5)", "", "| batch | eager ms | graph ms | speedup |", "|---|---|---|---|"]
        lines += [f"| {b} | {sweep[str(b)]['eager_ms']:.2f} | {sweep[str(b)]['graph_ms']:.2f} | {sweep[str(b)]['speedup']:.2f}x |" for b in bss]
        lines.append("")

    (BENCH / "summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(list(CHARTS.glob('*.png')))} charts and results/bench/summary.md")


if __name__ == "__main__":
    import sys

    sys.path.insert(0, str(ROOT))
    main()
